[package]
name = "duckdb_hudi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = true

[[example]]
name = "duckdb_hudi"
path = "src/wasm_lib.rs"
crate-type = ["staticlib"]

[dependencies]
duckdb = { version = "~1.10503.1", features = ["loadable-extension"] }
hudi = { git = "https://github.com/apache/hudi-rs", rev = "3abc4d5172434d58071ea8cd0ca5b6dbb5e191c7" }
tokio = { version = "1", features = ["rt-multi-thread"] }
url = "2"
vcpkg = "0.2.15"
